include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules for better code quality
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"