name: adaptive_text
description: A Flutter widget that intelligently adapts text display with line wrapping, font scaling, and truncation based on available space.
version: 1.0.0
homepage: https://github.com/MokuluaDev/adaptive_text
repository: https://github.com/MokuluaDev/adaptive_text
issue_tracker: https://github.com/MokuluaDev/adaptive_text/issues
documentation: https://github.com/MokuluaDev/adaptive_text#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
